[package]
name = "lithium"
version = "0.1.0"
edition = "2021"

[build-dependencies]
rustc_version = "0.4.1"

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ["cfg(nightly)", "cfg(backend, values(\"itanium\", \"panic\"))"]

[dev-dependencies]
anyhow = "1"

[dependencies]
typeid = "1.0.2"

[package.metadata."docs.rs"]
all-features = true
